name: LevelSignPlus
main: com.licrafter.levelSign.SignExtend
version: 3.1.5
author: shell
website: http://licrafter.com
description: prefix level
depend: [ProtocolLib,Residence,Vault]
softdepend: [PlaceholderAPI]
commands:
  level:
    description: basic command
    usage: §c/level help